name: mobilelapincouvert
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  http: ^1.3.0
  flutter_form_builder: ^9.7.0
  form_builder_validators: ^11.1.1
  easy_stepper: ^0.8.5+1
  flutter_swipe_button: ^2.1.3
  flutter_stripe: ^11.4.0
  pay: ^3.1.0
  dotted_line: ^3.2.3
  checkout_screen_ui: ^1.0.1
  lottie: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/adept_logo.jpg
    - assets/animations/jumping_rabbit.json
    - assets/images/placeholder_image.webp
    - assets/images/adeptinfo_badge.png
    - assets/images/profile_picture.webp
flutter_intl:
  enabled: true
