// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjI8TcLnKrtQ2TcxJlFDDsBQv9MZSmH2k',
    appId: '1:500670337319:web:8e5ff05cc787db32569902',
    messagingSenderId: '500670337319',
    projectId: 'projetfinallapincouvert',
    authDomain: 'projetfinallapincouvert.firebaseapp.com',
    storageBucket: 'projetfinallapincouvert.firebasestorage.app',
    measurementId: 'G-QJ6L3DXG3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN49DwiUJzgfmU_OhtIj1YEbcqzeH3w7c',
    appId: '1:500670337319:android:9f2ead2fabfb86ce569902',
    messagingSenderId: '500670337319',
    projectId: 'projetfinallapincouvert',
    storageBucket: 'projetfinallapincouvert.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT8xONjfh8CiWW0GTkN9nkkkhh9vFJosA',
    appId: '1:500670337319:ios:cf650a419a7b81d1569902',
    messagingSenderId: '500670337319',
    projectId: 'projetfinallapincouvert',
    storageBucket: 'projetfinallapincouvert.firebasestorage.app',
    iosBundleId: 'com.example.mobilelapincouvert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT8xONjfh8CiWW0GTkN9nkkkhh9vFJosA',
    appId: '1:500670337319:ios:cf650a419a7b81d1569902',
    messagingSenderId: '500670337319',
    projectId: 'projetfinallapincouvert',
    storageBucket: 'projetfinallapincouvert.firebasestorage.app',
    iosBundleId: 'com.example.mobilelapincouvert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjI8TcLnKrtQ2TcxJlFDDsBQv9MZSmH2k',
    appId: '1:500670337319:web:728a4e1dc1a8ddd5569902',
    messagingSenderId: '500670337319',
    projectId: 'projetfinallapincouvert',
    authDomain: 'projetfinallapincouvert.firebaseapp.com',
    storageBucket: 'projetfinallapincouvert.firebasestorage.app',
    measurementId: 'G-1R1ZRNLC0K',
  );

}